{% set version = "2024.3" %}
# Keep this in synch with https://github.com/KhronosGroup/SPIRV-Tools/blob/v2023.2/DEPS#L14
{% set headers_version = "1.3.290.0" %}

package:
  name: spirv-tools
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3961edff3410599112a50bfcda2d4a828f7cb12e8294ee0f6169976ef0532b83
  patches:
    - 0001-Get-package-version-and-description-from-conda-build.patch

build:
  run_exports:
    # They seem to be using calver, so their version numbers are not very informative
    # But we expect these to be rather stable
    # so lets try 'x' https://github.com/conda-forge/spirv-tools-feedstock/issues/3
    - {{ pin_subpackage('spirv-tools', 'x') }}
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
    - python
  host:
    - spirv-headers {{ headers_version }}
  run:

test:
  commands:
    - spirv-as -h

about:
  home: https://github.com/KhronosGroup/SPIRV-Tools
  license: Apache-2.0
  license_file: LICENSE
  summary: The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - isuruf
    - hmaarrfk
