{% set version = "2026.4" %}
# The SPIRV-Headers revision pinned by v{{ version }}'s DEPS.
{% set headers_version = "1.4.363.0" %}

package:
  name: spirv-tools
  version: "{{ version }}"

source:
  url: https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/v{{ version }}.zip
  sha256: c2399673510cfaa515e9197db18c2ae5860925f497ad8735c93f00f931c41cbd
  patches:
    - 0001-Get-package-version-and-description-from-conda-build.patch

build:
  run_exports:
    # They seem to be using calver, so their version numbers are not very informative
    # But we expect these to be rather stable
    # so lets try 'x' https://github.com/conda-forge/spirv-tools-feedstock/issues/3
    - {{ pin_subpackage('spirv-tools', 'x') }}
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
    - python
  host:
    - spirv-headers {{ headers_version }}
  run_constrained:
    - {{ pin_compatible('spirv-headers', max_pin='x.x.x.x') }}

test:
  requires:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
  files:
    - test/CMakeLists.txt
    - test/main.cpp
  commands:
    - spirv-as -h
    - cmake -G Ninja -S test -B test-build
    - cmake --build test-build
    - ./test-build/test-spirv-tools  # [unix]
    - test-build\\test-spirv-tools.exe  # [win]

about:
  home: https://github.com/KhronosGroup/SPIRV-Tools
  license: Apache-2.0
  license_file: LICENSE
  summary: The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
    - ZzEeKkAa
    - isuruf
    - hmaarrfk
    - JarrettSJohnson
    # baszalmstra is insterested in helping windows failures
    - baszalmstra
